
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 26 11:20:59 CST 2011
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AS = 60;
  public static final int FROM = 46;
  public static final int GT = 19;
  public static final int TIMESTAMP = 40;
  public static final int GROUP = 54;
  public static final int TABLE = 27;
  public static final int ASC = 58;
  public static final int COMMA = 5;
  public static final int SUM = 71;
  public static final int RPAREN = 8;
  public static final int ALL = 64;
  public static final int LT = 17;
  public static final int LPAREN = 7;
  public static final int DATETIME = 37;
  public static final int FALSE = 66;
  public static final int NOT = 30;
  public static final int FLOAT = 35;
  public static final int MIN = 70;
  public static final int STR = 3;
  public static final int NUM = 4;
  public static final int AUTOINCREMENT = 32;
  public static final int EQ = 15;
  public static final int MOD = 12;
  public static final int INTO = 43;
  public static final int SELECT = 67;
  public static final int TRUE = 65;
  public static final int PLUS = 10;
  public static final int INDEX = 51;
  public static final int EXISTS = 61;
  public static final int ORDER = 57;
  public static final int USE = 25;
  public static final int DELETE = 45;
  public static final int DECIMAL = 39;
  public static final int CHAR = 36;
  public static final int BOOLEAN = 38;
  public static final int DIV = 14;
  public static final int MAX = 69;
  public static final int MULT = 13;
  public static final int GTEQ = 20;
  public static final int DOT = 9;
  public static final int INT = 34;
  public static final int AVG = 73;
  public static final int NULL = 33;
  public static final int EOF = 0;
  public static final int SEMICOLON = 6;
  public static final int WHERE = 47;
  public static final int DEFAULT = 31;
  public static final int COUNT = 72;
  public static final int MINUS = 11;
  public static final int LTEQ = 18;
  public static final int UNIQUE = 50;
  public static final int IN = 63;
  public static final int OR = 22;
  public static final int SET = 49;
  public static final int error = 1;
  public static final int ON = 52;
  public static final int DESC = 59;
  public static final int ID = 2;
  public static final int DATABASE = 24;
  public static final int BY = 55;
  public static final int VALUES = 44;
  public static final int ANY = 62;
  public static final int CREATE = 23;
  public static final int VARCHAR = 41;
  public static final int UPDATE = 48;
  public static final int INSERT = 42;
  public static final int NEQ = 16;
  public static final int PRIMARY = 28;
  public static final int AND = 21;
  public static final int UMINUS = 68;
  public static final int DROP = 26;
  public static final int KEY = 29;
  public static final int HAVING = 56;
  public static final int DISTINCT = 53;
}

